services:
  database:
    image: postgres:latest
    container_name: postgres_db
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: supplymanager_db
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: